name: daily-devcard
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Fetch vertical devcard
        uses: dailydotdev/action-devcard@3.2.1
        with:
          user_id: ${{ secrets.USER_ID }}
          dryrun: true
          commit_filename: devcard-vert.png

      - name: Fetch horizontal devcard
        uses: dailydotdev/action-devcard@3.2.1
        with:
          user_id: ${{ secrets.USER_ID }}
          dryrun: true
          type: "wide"
          commit_filename: devcard-horiz.png

      - name: Move DevCards to the repository root
        run: |
          mv /tmp/devcard-horiz.png .
          mv /tmp/devcard-vert.png .

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'devcard-vert.png devcard-horiz.png'
          default_author: github_actions
          message: 'chore: update devcards'
